name: Trigger auto deployment for rs-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rs-container-app-AutoDeployTrigger-64879403-ceb4-41eb-b3d3-97703adf6f3a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RSCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RSCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RSCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.RSCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RSCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: rs-container-app
          resourceGroup: genai3x-edx-course-resource-group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


